// TODO: Add API_BASE_URL

// Auth Status Actions
export const AUTH_STATUS_REQUESTED = 'AUTH_STATUS_REQUESTED';
export const AUTH_STATUS_SUCCEEDED = 'AUTH_STATUS_SUCCEEDED';
export const AUTH_STATUS_FAILED = 'AUTH_STATUS_FAILED';

// Auth Login Actions
export const AUTH_LOGIN_REQUESTED = 'AUTH_LOGIN_REQUESTED';
export const AUTH_LOGIN_SUCCEEDED = 'AUTH_LOGIN_SUCCEEDED';
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';

// Auth Logout Actions
export const AUTH_LOGOUT_REQUESTED = 'AUTH_LOGOUT_REQUESTED';
export const AUTH_LOGOUT_SUCCEEDED = 'AUTH_LOGOUT_SUCCEEDED';
export const AUTH_LOGOUT_FAILED = 'AUTH_LOGOUT_FAILED';

// User List Actions
export const USER_LIST_REQUESTED = 'USER_LIST_REQUESTED';
export const USER_LIST_SUCCEEDED = 'USER_LIST_SUCCEEDED';
export const USER_LIST_FAILED = 'USER_LIST_FAILED';

// User Data Actions
export const USER_DATA_REQUESTED = 'USER_DATA_REQUESTED';
export const USER_DATA_SUCCEEDED = 'USER_DATA_SUCCEEDED';
export const USER_DATA_FAILED = 'USER_DATA_FAILED';

// Get Assessment Data
export const ASSESSMENT_LIST_REQUESTED = 'ASSESSMENT_LIST_REQUESTED';
export const ASSESSMENT_LIST_SUCCEEDED = 'ASSESSMENT_LIST_SUCCEEDED';
export const ASSESSMENT_LIST_FAILED = 'ASSESSMENT_LIST_FAILED';

// Get All Assessment Data
export const ASSESSMENT_ALL_REQUESTED = 'ASSESSMENT_ALL_REQUESTED';
export const ASSESSMENT_ALL_SUCCEEDED = 'ASSESSMENT_ALL_SUCCEEDED';
export const ASSESSMENT_ALL_FAILED = 'ASSESSMENT_ALL_FAILED';
