// Auth Status Actions
export const AUTH_STATUS_REQUESTED = 'AUTH_STATUS_REQUESTED';
export const AUTH_STATUS_SUCCEEDED = 'AUTH_STATUS_SUCCEEDED';
export const AUTH_STATUS_FAILED = 'AUTH_STATUS_FAILED';

// Auth Login Actions
export const AUTH_LOGIN_REQUESTED = 'AUTH_LOGIN_REQUESTED';
export const AUTH_LOGIN_SUCCEEDED = 'AUTH_LOGIN_SUCCEEDED';
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';

// User List Actions
export const USER_LIST_REQUESTED = 'USER_LIST_REQUESTED';
export const USER_LIST_SUCCEEDED = 'USER_LIST_SUCCEEDED';
export const USER_LIST_FAILED = 'USER_LIST_FAILED';

// User Data Actions
export const USER_DATA_REQUESTED = 'USER_DATA_REQUESTED';
export const USER_DATA_SUCCEEDED = 'USER_DATA_SUCCEEDED';
export const USER_DATA_FAILED = 'USER_DATA_FAILED';
